---
- name: tagging in ansible
  hosts: all
  tasks:
   - name: install tree
     apt:
      name: install tree
      state: present
     tags: tree install
   - name: creation user
     user: 
      name: ranu
      password: janu
     tags: user creat
   - name: copy/etc/password file
     copy:
      src: /etc/password
      dest: /tmp
