---
- name: create user
  hosts: all
  tasks:
    - name: user
      user:
       name: sai
       password: intelliqit
       uid: 3421
       home: /home/ubuntu/sai
       comment: "love you"
       shell: /bin/bash
...