---
- name: implementing handlers
  hosts: all
  tasks:
   - name: install apache2
     apt:
      name: apache2
      state: absent
     notify: check url response
   - name: Edit index.html file
     copy: 
      content: "intelliqit"
      dest: /var/www/html/index.html
     notify: restart apache2
     handlers:
   - name: restart apache2
     service:
      name: apache2
      state: restarted
   - name: check url responce
     uri:
      url: "{{item}}"
      status_code: 200
     with_items:
      - http://172.31.26.195
      - http://172.31.30.174