---
- name: jenkins install 
  hosts: jenkins server
  tasks:
   - name: install required 
     apt:
      name: "{{item.a}}"
      state: present
      update_cache: "{{item.b}}"
     with_items: 
      - {a: openjdk-8-jdk,b: yes}
      - {a: git,b: b:no}
      - {a: maven,b: no}
   - name: jenkins download jenkins.war
     uri:
      get_url: 
       url: https://get.jenkins.io/war-stable/2.332.3/jenkins.war
       dest: /home/ubuntu
       
    