---
- name: install software
  hosts: all
  tasks:
   - name: software install
     apt:
      name: "{{a}}"
      state: "{{b}}"
      update_cache: "{{c}}"
     with_items:
      - {a: tree,b: present,c: no}
      - {a: openjdk-8-jdk,b: absent,c: no}
      - {a: maven,b: latest,c: yes}
       
