---
- name: check url response of apache2 on all managed nodes
  uri: 
   url: "{{item}}"
   status_code: 200
  with_items:
   - http://172.31.26.148
   - http://172.31.26.195
   - http://172.31.30.174
   