---
- name: condition apache2 using playbook
  hosts: all
  tasks:
   - name: call multiple child playbook
     include: "{{item}}"
     with_items:
      - install_apache.yml
      - edit_index.yml
      - service.yml
      - check_url_responce.yml
      
